# import pygame as pg
#
#
# def rotate(image, rect, angle):
#     """Rotate the image while keeping its center."""
#     # Rotate the original image without modifying it.
#     new_image = pg.transform.rotate(image, angle)
#     # Get a new rect with the center of the old rect.
#     rect = new_image.get_rect(center=rect.center)
#     return new_image, rect
#
#
# def main():
#     clock = pg.time.Clock()
#     screen = pg.display.set_mode((640, 480))
#     gray = pg.Color('gray15')
#     blue = pg.Color('dodgerblue2')
#
#     image = pg.Surface((320, 200), pg.SRCALPHA)
#     pg.draw.polygon(image, blue, ((0, 0), (320, 100), (0, 200)))
#     # Keep a reference to the original to preserve the image quality.
#     orig_image = image
#     rect = image.get_rect(center=(320, 240))
#     angle = 0
#
#     done = False
#     while not done:
#         for event in pg.event.get():
#             if event.type == pg.QUIT:
#                 done = True
#
#         angle += 2
#         image, rect = rotate(orig_image, rect, angle)
#
#         screen.fill(gray)
#         screen.blit(image, rect)
#         pg.display.flip()
#         clock.tick(30)
#
#
# if __name__ == '__main__':
#     pg.init()
#     main()
#     pg.quit()


{'level_name': 'level 3', 'timer': 0, 'tip': 'press space to fire equipment', 'end_level_hint': 'that was fun!', 'finished_intro': True, 'intro': 'BEWARE!', 'intro_timer': 0, 'intro_time': 1000, 'screen_width': 900, 'screen_height': 700, 'in_game_hint': [[0, 5000, 'red is fragile', 200, 350.0]], 'player_mlee_dmg': 50, 'score_factor': 1.0, 'score': 2315.0, 'player_max_health': 4000, 'player_health': 1850, 'health_bar_length': 300, 'health_ratio': 13.333333333333334, 'player_mlee_timer': 0, 'player_mleed': True, 'player_mlee_countdown': 5000, 'laser_countdown': 100, 'laser_speed': -19, 'laser_speed_rate': 1.0375, 'laser_dmg': 500, 'laser_type': 4, 'laser_speed_score': 4100, 'laser_countdown_rate': -25, 'laser_min_countdown': 50, 'laser_max_speed': -30, 'equipment_speed': -8, 'equipment_dmg': 90, 'equipment_cooldown': 750, 'equipment_type': 2, 'equipment_is_ready': True, 'equipment_timer': 0, 'block_size': 7, 'block_shape': ['    xxxxxxx', '   xxxxxxxxx', '  xxxxxxxxxxx', ' xxxxxxxxxxxxx', 'xxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxx', 'xxxx        xxxx', 'xxx          xxx'], 'whole_block_size': 91, 'block_amount': 6, 'min_space_between': 100, 'max_space_between': 200, 'enemy_y_speed_rate': 1, 'died_enemies': 58, 'extra_enemy_spawn_min_time': 7000, 'extra_enemy_spawn_max_time': 15000, 'extra_enemy_spawn_time': 13270, 'extra_enemy_timer': 0, 'extra_enemy_speed': 3, 'extra_enemy_bonus': 50, 'extra_enemy_health': 60, 'enemy_explosion_timer': 0, 'collectible_speed': 1, 'coin_rate': 2, 'coins': 725, 'mouse_clicked': False, 'is_paused': False, 'end_level': False, 'game_over': False, 'enemies': [<source.enemy.EnemyArmy object at 0x00000262AA6E31C0>], 'enemy_amount': 96, 'spawned_waves': 1, 'max_waves': 1, 'spawn_timer': 0, 'end_level_timer': 0, 'finished_timer': 0}
{
    "level_name": "level 3",
    "timer": 0,
    "tip": "press space to fire equipment",
    "end_level_hint": "that was fun!",
    "finished_intro": true,
    "intro": "BEWARE!",
    "intro_timer": 0,
    "intro_time": 1000,
    "screen_width": 900,
    "screen_height": 700,
    "in_game_hint": [
        [
            0,
            5000,
            "red is fragile",
            200,
            350.0
        ]
    ],
    "player_mlee_dmg": 50,
    "score_factor": 1.0,
    "score": 2315.0,
    "player_max_health": 4000,
    "player_health": 1850,
    "health_bar_length": 300,
    "health_ratio": 13.333333333333334,
    "player_mlee_timer": 0,
    "player_mleed": true,
    "player_mlee_countdown": 5000,
    "laser_countdown": 100,
    "laser_speed": -19,
    "laser_speed_rate": 1.0375,
    "laser_dmg": 500,
    "laser_type": 4,
    "laser_speed_score": 4100,
    "laser_countdown_rate": -25,
    "laser_min_countdown": 50,
    "laser_max_speed": -30,
    "equipment_speed": -8,
    "equipment_dmg": 90,
    "equipment_cooldown": 750,
    "equipment_type": 2,
    "equipment_is_ready": true,
    "equipment_timer": 0,
    "block_size": 7,
    "block_shape": [
        "    xxxxxxx",
        "   xxxxxxxxx",
        "  xxxxxxxxxxx",
        " xxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxx",
        "xxxxxxxxxxxxxxxx",
        "xxxx        xxxx",
        "xxx          xxx"
    ],
    "whole_block_size": 91,
    "block_amount": 6,
    "min_space_between": 100,
    "max_space_between": 200,
    "enemy_y_speed_rate": 1,
    "died_enemies": 58,
    "extra_enemy_spawn_min_time": 7000,
    "extra_enemy_spawn_max_time": 15000,
    "extra_enemy_spawn_time": 13270,
    "extra_enemy_timer": 0,
    "extra_enemy_speed": 3,
    "extra_enemy_bonus": 50,
    "extra_enemy_health": 60,
    "enemy_explosion_timer": 0,
    "collectible_speed": 1,
    "coin_rate": 2,
    "coins": 725,
    "mouse_clicked": false,
    "is_paused": false,
    "end_level": false,
    "game_over": false,
    "enemies": [
        {
            "enemy_packs": [
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ],
                [
                    {
                        "sp": {
                            "x": 229,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 309,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 469,
                            "y": 105
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    null,
                    {
                        "sp": {
                            "x": 629,
                            "y": 215
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 709,
                            "y": 545
                        },
                        "color": "r",
                        "timer": 0,
                        "max_hp": 50,
                        "hp": 50,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 15,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 500,
                        "mlee_time": 5000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    },
                    {
                        "sp": {
                            "x": 789,
                            "y": 655
                        },
                        "color": "g",
                        "timer": 0,
                        "max_hp": 500,
                        "hp": 500,
                        "dmg": 50,
                        "mlee_dmg": 150,
                        "score": 100,
                        "mlee_timer": 0,
                        "mleed": false,
                        "cooldown": 2000,
                        "mlee_time": 10000,
                        "another_img": null,
                        "another_rect": null,
                        "normal_ani": null,
                        "ani_timer": 0,
                        "ani_change": 900,
                        "rotate_angle": 0,
                        "rotate_speed": 0.2,
                        "rotate_timer": 0,
                        "rotate_countdown": null,
                        "ani": null
                    }
                ]
            ],
            "representation": [
                [
                    "r",
                    "r",
                    "",
                    "r",
                    "",
                    "r",
                    "r",
                    "r"
                ],
                [
                    "r",
                    "r",
                    "",
                    "r",
                    "",
                    "r",
                    "r",
                    "r"
                ],
                [
                    "y",
                    "",
                    "",
                    "",
                    "",
                    "g",
                    "",
                    "g"
                ],
                [
                    "g",
                    "",
                    "",
                    "",
                    "",
                    "r",
                    "",
                    "r"
                ],
                [
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "y"
                ],
                [
                    "b",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "b"
                ],
                [
                    "g",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "g"
                ],
                [
                    "r",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "r",
                    "r"
                ],
                [
                    "y",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "g",
                    "g"
                ],
                [
                    "g",
                    "y",
                    "",
                    "",
                    "",
                    "",
                    "r",
                    "r"
                ],
                [
                    "y",
                    "y",
                    "",
                    "",
                    "",
                    "",
                    "",
                    ""
                ],
                [
                    "g",
                    "g",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "g"
                ]
            ],
            "enemy_shoot_cooldown": 1,
            "enemy_laser_speed": 8,
            "enemy_cooldown_timer": 0,
            "enemy_y_speed": 1,
            "enemy_y_timer": 0,
            "enemy_y_speed_countdown": 4000,
            "enemy_move_down_already": false,
            "enemy_y_speed_drop_time": 10,
            "enemy_y_speed_drop_rate": 10,
            "enemy_x_speed": 1,
            "enemy_x_timer": 0,
            "enemy_x_speed_countdown": 0,
            "enemy_move_x_already": false,
            "enemy_x_speed_drop_time": -159,
            "enemy_x_speed_drop_rate": 1,
            "enemy_y_lower_constraint": null,
            "enemy_y_upper_constraint": null,
            "enemy_x_left_constraint": -15,
            "enemy_x_right_constraint": 915,
            "enemy_amount": 38
        }
    ],
    "enemy_amount": 96,
    "spawned_waves": 1,
    "max_waves": 1,
    "spawn_timer": 0,
    "end_level_timer": 0,
    "finished_timer": 0
}

